[build-system]
requires = ["setuptools>=83.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "deltakit-visualise"
version = "0.0.1"
description = "Deltakit (component deltakit-visualise)"
readme = "README.md"
requires-python = ">=3.10, <3.15"
license = "Apache-2.0"
license-files = ["LICENSE"]

authors = [{ name = "Deltakit Team", email = "deltakit@riverlane.com" }]

classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Quantum Computing",
  "Typing :: Typed",
]

dependencies = []

[project.urls]
Homepage = "https://github.com/Deltakit/deltakit"
"Bug Tracker" = "https://github.com/Deltakit/deltakit/issues"
Changelog = "https://github.com/Deltakit/deltakit/releases"

[dependency-groups]
test = [
  "numpy >=1.25, <3",
  "numpy >=1.26, <3; python_version >= '3.12'",
  "numpy >=2.1, <3; python_version >= '3.13'",
  "numpy >=2.3.4, <3; python_version >= '3.14'",
  "pytest>=9.1.1,<10",
  "pytest-cov>=7.1.0,<8",
  "pytest-skip-slow>=1.1.0,<1.2",
  "coverage>=7.15.3,<8",
  "pytest-mock>=3.15.1",
  "pytest-lazy-fixtures>=1.4.0",
]
lint = [
  "mypy>=2.3.0,<3.0",
  "ruff==0.16.1",
  "typos>=1.49.0,<2",
  "deptry>=0.25.1,<0.26",
  "pydoclint>=0.9.1,<0.10",
]
security = ["bandit[toml]>=1.9.4,<2", "pip-audit>=2.10.1,<3"]
dev = [
  { include-group = "test" },
  { include-group = "lint" },
  { include-group = "security" },
  "pre-commit>=4.6.1,<5",
  "validate-pyproject>=0.25,<0.26",
]
release = [
  "python-semantic-release >=10.6.1, <11",
  "packaging>=26.2,<27",
  "requests>=2.34.2",
  "tomlkit>=0.15.1,<0.16",
]

[tool.deptry]
known_first_party = ["deltakit_visualise"]

[tool.mypy]
files = "src/**/*.py"

[tool.pytest.ini_options]
testpaths = ["./tests/"]

[tool.pydoclint]
style = 'google'
exclude = '\.git|\.venv.*'
# We do not want type hints to be duplicated in docstrings.
arg-type-hints-in-docstring = false
check-return-types = false
check-yield-types = false
# Ensure that Google style is used
check-style-mismatch = true
# Short docstrings are an open door for circumventing the linter.
skip-checking-short-docstrings = false
# For the moment, we have a baseline of documentation format errors. Eventually, this will
# be removed.
baseline = ".pydoclint_baseline.txt"

[tool.typos.default]
locale = 'en-gb'
extend-ignore-re = [
  # Ignore jupyter notebook cell IDs
  "\"id\"\\s*:\\s*\"[0-9a-f]{8,}\"",
]

[tool.typos.default.extend-words]
# Don't correct "iy" - often used in the context of "probability of an IY operation"
iy = "iy"
iz = "iz"
IZ = "IZ"
anc = "anc"
BA = "BA"
youre = "you're"
distribtuion = "distribution"
interm = "interm"
ket = "ket"
ND = "ND"                         # part of NDArray
Alise = "Alise"
DEPOLARIZE = "DEPOLARIZE"
depolarization = "depolarization"
depolarizing = "depolarizing"
Authorization = "Authorization"   # Web-related field.
color = "color"                   # Used in matplotlib and stim APIs.
colors = "colors"
optimize = "optimize"             # scipy.optimize
ax = "ax"                         # Typical naming for matplotlib Axes instances.
center = "center"
stabilizer = "stabilizer"
stabilizers = "stabilizers"
synchronize = "synchronize"       # multiprocessing import
neighbors = "neighbors"
capitalize = "capitalize"
labeled = "labeled"
labeler = "labeler"
unrealized = "unrealized"
writeable = "writeable"           # Used in numpy APIs.
CPY = "CPY"                       # A ruff rule identifier
minimize = "minimize"
Normalize = "Normalize"

[tool.typos.files]
# Paths/patterns to exclude from spell checking
extend-exclude = ["**/LICENSE", "**/*.html"]