// RUN: %visualise_patch "%s" -O %t.json && %filecheck "%s" --input-file %t.json
builtin.module {
    %q1, %q2, %q3, %q4, %q5, %q6, %q7 = qcore.alloc_qubit<coords=[(0.5, 0.5), (0.5, 1.5), (1.5, 0.5), (1.5, 1.5), (1.0, 1.0), (1.0, 2.0), (1.0, 0.0)]> -> !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit
    %qreg = qcore.pack_qubit_reg(%q1, %q2, %q3, %q4, %q5, %q6, %q7) -> !qcore.qubit_reg<7>
    %p0 = log_asm.cast(%qreg : !qcore.qubit_reg<7>) -> !log_asm.patch.rot_planar<size=(2, 2), location=(0.0, 0.0), orient=v_z>
    %p0_1 = log_asm.prepare<Z> (%p0 : !log_asm.patch.rot_planar<size=(2, 2), location=(0.0, 0.0), orient=v_z>)
    %p0_2 = log_asm.cast(%p0_1 : !log_asm.patch.rot_planar<size=(2, 2), location=(0.0, 0.0), orient=v_z>) -> !qcore.qubit_reg<7>
    %p0_3, %p0_4, %p0_5, %p0_6, %p0_7, %p0_8, %p0_9 = qcore.unpack_qubit_reg(%p0_2 : !qcore.qubit_reg<7>)
    %p0_10, %p0_11, %p0_12, %p0_13, %p0_14, %p0_15, %p0_16 = qstruct.repeat<46> (%p0_3, %p0_4, %p0_5, %p0_6, %p0_7, %p0_8, %p0_9 : !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit) -> !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit {
        ^bb0(%0: !qcore.qubit, %1: !qcore.qubit, %2: !qcore.qubit, %3: !qcore.qubit, %4: !qcore.qubit, %5: !qcore.qubit, %6: !qcore.qubit):
        %7, %8, %9, %10, %11, %12, %13, %14, %15, %16 = qstruct.circuit(%0, %1, %2, %3, %4, %5, %6 : !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit) -> !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, i1, i1, i1 {
            ^bb1(%17: !qcore.qubit, %18: !qcore.qubit, %19: !qcore.qubit, %20: !qcore.qubit, %21: !qcore.qubit, %22: !qcore.qubit, %23: !qcore.qubit):
            %24, %25, %26 = plaquette.round(%17, %18, %19, %20, %21, %22, %23) -> i1, i1, i1 {
                ^bb2(%27: !qcore.qubit, %28: !qcore.qubit, %29: !qcore.qubit, %30: !qcore.qubit, %31: !qcore.qubit, %32: !qcore.qubit, %33: !qcore.qubit):
                %34 = plaquette.plaquette<[X0 X1 X2 X3 : 4]> on (%28, %30, %27, %29) using (%31) -> i1
                plaquette.yield %34 : i1
            } {
                ^bb3(%35: !qcore.qubit, %36: !qcore.qubit, %37: !qcore.qubit, %38: !qcore.qubit, %39: !qcore.qubit, %40: !qcore.qubit, %41: !qcore.qubit):
                %42 = plaquette.plaquette<[Z0 Z1 : 2]> on (%36, %38) using (%40) -> i1
                plaquette.yield %42 : i1
            } {
                ^bb4(%43: !qcore.qubit, %44: !qcore.qubit, %45: !qcore.qubit, %46: !qcore.qubit, %47: !qcore.qubit, %48: !qcore.qubit, %49: !qcore.qubit):
                %50 = plaquette.plaquette<[Z0 Z1 : 2]> on (%43, %45) using (%49) -> i1
                plaquette.yield %50 : i1
            }
            qstruct.yield %17, %18, %19, %20, %21, %22, %23, %24, %25, %26 : !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, i1, i1, i1
        }
        qstruct.yield %7, %8, %9, %10, %11, %12, %13 : !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit, !qcore.qubit
    }
    %p0_17 = qcore.pack_qubit_reg(%p0_10, %p0_11, %p0_12, %p0_13, %p0_14, %p0_15, %p0_16) -> !qcore.qubit_reg<7>
    %p0_18 = log_asm.cast(%p0_17 : !qcore.qubit_reg<7>) -> !log_asm.patch.rot_planar<size=(2, 2), location=(0.0, 0.0), orient=v_z>
    %log = log_asm.measure<Z> (%p0_18 : !log_asm.patch.rot_planar<size=(2, 2), location=(0.0, 0.0), orient=v_z>) -> i1
}
// CHECK: [{"round": 1,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 2,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 3,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 4,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 5,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 6,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 7,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 8,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 9,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 10,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 11,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 12,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 13,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 14,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 15,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 16,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 17,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 18,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 19,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 20,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 21,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 22,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 23,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 24,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 25,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 26,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 27,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 28,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 29,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 30,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 31,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 32,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 33,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 34,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 35,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 36,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 37,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 38,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 39,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 40,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 41,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 42,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 43,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 44,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 45,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]},
// CHECK: {"round": 46,
// CHECK-SAME: "qubits": [{"id": "q_0", "type": "data", "coordinates": [0.5, 0.5]}, {"id": "q_1", "type": "data", "coordinates": [1.5, 0.5]}, {"id": "q_2", "type": "data", "coordinates": [0.5, 1.5]}, {"id": "q_3", "type": "data", "coordinates": [1.5, 1.5]}, {"id": "q_4", "type": "ancilla", "coordinates": [1.0, 0.0]}, {"id": "q_5", "type": "ancilla", "coordinates": [1.0, 1.0]}, {"id": "q_6", "type": "ancilla", "coordinates": [1.0, 2.0]}],
// CHECK-SAME: "patches": [{"plaquettes": [{"id": 0, "colour": "red", "shape": "square", "weight": 4, "coordinates": ["q_0", "q_1", "q_2", "q_3"]}, {"id": 1, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_2", "q_3", "q_6"]}, {"id": 2, "colour": "blue", "shape": "semicircle", "weight": 2, "coordinates": ["q_0", "q_1", "q_4"]}]}]}
// CHECK: ]
